from .end_statement import *
from .input_statement import *
from .let_statement import *
from .print_statement import *
from .rem_statement import *
from .return_statement import *
from .stop_statement import *
from .if_statement import *
from .for_statement import *
from .next_statement import *
from .gosub_statement import *
from .goto_statement import *
from .on_statement import *
from .def_statement import *
from .dim_statement import *
from .read_statement import *